
Flowpack:
  SingleSignOn:
    Server:
      server:
        keyPairFingerprint: bb5abb57faa122cc031e3c904db3d751
        serviceBaseUri: 'http://ssoserver/test/sso'
      log:
        backend: Neos\Flow\Log\Backend\NullBackend
    Client:
      client:
        serviceBaseUri: 'http://ssoclient/sso'
        publicKeyFingerprint: bb45dfda9f461c22cfdd6bbb0a252d8e
      server:
        TestServer:
          publicKeyFingerprint: bb5abb57faa122cc031e3c904db3d751
          serviceBaseUri: 'http://ssoserver/test/sso'
Neos:
  Flow:
    security:
      cryptography:
        RSAWalletServicePHP:
          keystorePath: '%FLOW_PATH_DATA%Temporary/Testing/RsaWalletData'
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: WebRedirect
            entryPointOptions:
              uri: login
