#
# Default Settings for Flowpack.SingleSignOn.Server
#

Flowpack:
  SingleSignOn:
    Server:
      server:
        serviceBaseUri: ''
        keyPairFingerprint: ''
      log:
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/SingleSignOn_Server.log'
          createParentDirectories: true
          severityThreshold: '%LOG_WARN%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logMessageOrigin: false
        logRequestSigning: false
      accountMapper:
        configuration: null
Neos:
  Flow:
    security:
      firewall:
        filters:
          ssoServerSignedRequests:
            patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\ConjunctionPattern
            patternValue:
              patterns:
                -
                  patternType: ControllerObjectName
                  patternValue: Flowpack\SingleSignOn\Server\Controller\(AccessToken|Session)Controller
                -
                  patternType: Flowpack\SingleSignOn\Client\Security\RequestPattern\SignedRequestPattern
                  patternValue:
                    resolverType: Flowpack\SingleSignOn\Server\Security\RequestPattern\SsoClientPublicKeyResolver
            interceptor: AccessDeny
    object:
      excludeClasses:
        mockery.mockery:
          - '.*'
